version: '2'

services:
  cqhttp:
    image: richardchien/cqhttp:latest
    ports:
      - 9000:9000  # VNC port
    volumes:
      - ./coolq:/home/user/coolq
    environment:
      VNC_PASSWD: MAX8char  # change it
      COOLQ_URL: http://dlsec.cqp.me/cqa-tuling  # 'cqa-tuling' for CoolQ Air and 'cqp-tuling' for CoolQ Pro
      CQHTTP_POST_URL: http://koishi:8080
      CQHTTP_SERVE_DATA_FILES: "true"

  koishi:
    image: koishijs/koishi:latest
    volumes:
      - ./koishi:/config
    environment:
      TYPE: http
      SERVER: http://cqhttp:5700